# Codecov configuration for mobile-only Flutter app
coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 2%
    patch:
      default:
        target: 80%
        
ignore:
  - "lib/firebase_options.dart"
  - "lib/main.dart"
  - "**/*.g.dart"
  - "**/*.freezed.dart"
  - "**/generated/**"
  - "test/**"
  - "android/**"
  - "ios/**"
  
comment:
  layout: "header, diff, flags, files"
  behavior: default
  require_changes: false